services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    networks:
      - tfo-net
    ports:
      - 27017:27017
    restart: always
    volumes:
      - tfo-db:/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

networks:
  tfo-net:
    name: tfo-net

volumes:
  tfo-db: