services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    # expose:
    #   - 27017
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - tfo-db:/mongo

volumes:
  tfo-db: