# docker build -t postgres-tfo-db .
# docker run -d --name postgres-tfo -p 5432:5432 postgres-tfo-db

FROM postgres:alpine

ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_DB test